services:
    base.listener.fdc:
        class: Base\CoreBundle\Listener\FDCListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }