services:
  base.listener.media_video:
        class: Base\CoreBundle\Listener\MediaVideoListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

  base.listener.news:
        class: Base\CoreBundle\Listener\NewsListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }