services:
    base.search.repository:
        class: Base\CoreBundle\Component\Repository\SearchRepository
        arguments: ['@fos_elastica.finder.fdc']
    base.transformers.model.media:
        class: Base\CoreBundle\Transformer\MediaToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
    base.transformers.model.film:
        class: Base\CoreBundle\Transformer\FilmFilmToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
    base.transformers.model.statement:
        class: Base\CoreBundle\Transformer\StatementToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
    base.transformers.model.info:
        class: Base\CoreBundle\Transformer\InfoToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
    base.transformers.model.news:
        class: Base\CoreBundle\Transformer\NewsToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
    base.transformers.model.event:
        class: Base\CoreBundle\Transformer\EventToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
    base.transformers.model.quiet_property_accessor:
        class: Base\CoreBundle\Transformer\QuietPropertyAccessor
    base.transformers.model.nullable:
        class: FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer
        arguments: [[], "@event_dispatcher"]
        calls:
            - [setPropertyAccessor, ["@base.transformers.model.quiet_property_accessor"]]