services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    base.twig.news_instance_of_extension:
        class: Base\CoreBundle\Twig\Extension\NewsInstanceOfExtension
        tags:
            - { name: twig.extension }

    base.twig.news_widget_instance_of_extension:
        class: Base\CoreBundle\Twig\Extension\NewsWidgetInstanceOfExtension
        tags:
            - { name: twig.extension }

    base.twig.statement_instance_of_extension:
        class: Base\CoreBundle\Twig\Extension\StatementInstanceOfExtension
        tags:
            - { name: twig.extension }

    base.twig.trans_fallback_extension:
        class: Base\CoreBundle\Twig\Extension\TransFallbackExtension
        tags:
            - { name: twig.extension }
        arguments: [%locale_fallback%, @request_stack]

    base.twig.content_lang_extension:
        class: Base\CoreBundle\Twig\Extension\ContentLangExtension
        arguments: [%locale_fallback%, @request_stack]
        tags:
            - { name: twig.extension }

    base.twig.film_function_extension:
        class: Base\CoreBundle\Twig\Extension\FilmFunctionExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    base.twig.film_media_extension:
        class: Base\CoreBundle\Twig\Extension\FilmMediaExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }