services:
    base.validator.locale:
        class: Base\CoreBundle\Validator\Constraints\LocaleValidator
        tags:
            - { name: validator.constraint_validator, alias: base_validator_locale }
        calls:
            - ['setLocales', ['%locales%']]