security:
    role_hierarchy:
        ROLE_FDC_ADMIN:
            - ROLE_ADMIN
            - ROLE_FDC_SETTINGS
            - ROLE_FDC_TRANSLATOR_MASTER
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ADMIN
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_ADMIN
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_ADMIN
            - ROLE_BASE_ADMIN_HOMEPAGE_ADMIN
            - ROLE_BASE_ADMIN_TAG_ADMIN
            - ROLE_BASE_ADMIN_WEB_TV_ADMIN
            - ROLE_BASE_ADMIN_EVENT_ADMIN
            - ROLE_BASE_ADMIN_THEME_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_ARTICLE_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_VIDEO_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_IMAGE_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_AUDIO_ADMIN
            - ROLE_BASE_ADMIN_THEME_ADMIN
            - ROLE_BASE_ADMIN_NEWS_ARTICLE_ADMIN
            - ROLE_BASE_ADMIN_NEWS_VIDEO_ADMIN
            - ROLE_BASE_ADMIN_NEWS_IMAGE_ADMIN
            - ROLE_BASE_ADMIN_NEWS_AUDIO_ADMIN
            - ROLE_BASE_ADMIN_MEDIA_IMAGE_ADMIN
            - ROLE_BASE_ADMIN_MEDIA_AUDIO_ADMIN
            - ROLE_BASE_ADMIN_MEDIA_VIDEO_ADMIN
            - ROLE_BASE_ADMIN_FILM_FILM_ADMIN
            - ROLE_BASE_ADMIN_FILM_PERSON_ADMIN
            - ROLE_BASE_ADMIN_FILM_ATELIER_ADMIN
            - ROLE_BASE_ADMIN_COUNTRY_ADMIN
            - ROLE_BASE_ADMIN_MEDIA_TAG_ADMIN
            - ROLE_BASE_ADMIN_MEDIA_ADMIN
            - ROLE_BASE_ADMIN_GALLERY_ADMIN
            - ROLE_BASE_ADMIN_GALLERY_MEDIA_ADMIN
            - ROLE_BASE_ADMIN_NEWS_ADMIN
            - ROLE_BASE_ADMIN_NEWS_TAG_ADMIN
            - ROLE_BASE_ADMIN_NEWS_NEWS_ASSOCIATED_ADMIN
            - ROLE_BASE_ADMIN_NEWS_FILM_FILM_ASSOCIATED_ADMIN
            - ROLE_BASE_ADMIN_NEWS_FILM_PROJECTION_ASSOCIATED_ADMIN
            - ROLE_BASE_ADMIN_FILM_FILM_MEDIA_ADMIN
            - ROLE_BASE_ADMIN_FILM_MEDIA_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_TAG_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_STATEMENT_ASSOCIATED_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_FILM_FILM_ASSOCIATED_ADMIN
            - ROLE_BASE_ADMIN_STATEMENT_FILM_PROJECTION_ASSOCIATED_ADMIN
            - ROLE_BASE_ADMIN_SOCIAL_WALL_ADMIN

        ROLE_FDC_WRITER:
            - ROLE_ADMIN
            - ROLE_FDC_TRANSLATOR_ES
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_WRITER
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_WRITER
            - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_WRITER
            - ROLE_BASE_ADMIN_HOMEPAGE_WRITER
            - ROLE_BASE_ADMIN_TAG_WRITER
            - ROLE_BASE_ADMIN_WEB_TV_WRITER
            - ROLE_BASE_ADMIN_EVENT_WRITER
            - ROLE_BASE_ADMIN_THEME_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_ARTICLE_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_VIDEO_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_IMAGE_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_AUDIO_WRITER
            - ROLE_BASE_ADMIN_THEME_WRITER
            - ROLE_BASE_ADMIN_NEWS_ARTICLE_WRITER
            - ROLE_BASE_ADMIN_NEWS_VIDEO_WRITER
            - ROLE_BASE_ADMIN_NEWS_IMAGE_WRITER
            - ROLE_BASE_ADMIN_NEWS_AUDIO_WRITER
            - ROLE_BASE_ADMIN_MEDIA_IMAGE_WRITER
            - ROLE_BASE_ADMIN_MEDIA_AUDIO_WRITER
            - ROLE_BASE_ADMIN_MEDIA_VIDEO_WRITER
            - ROLE_BASE_ADMIN_MEDIA_TAG_WRITER
            - ROLE_BASE_ADMIN_MEDIA_WRITER
            - ROLE_BASE_ADMIN_GALLERY_WRITER
            - ROLE_BASE_ADMIN_GALLERY_MEDIA_WRITER
            - ROLE_BASE_ADMIN_NEWS_WRITER
            - ROLE_BASE_ADMIN_NEWS_TAG_WRITER
            - ROLE_BASE_ADMIN_NEWS_NEWS_ASSOCIATED_WRITER
            - ROLE_BASE_ADMIN_NEWS_FILM_FILM_ASSOCIATED_WRITER
            - ROLE_BASE_ADMIN_NEWS_FILM_PROJECTION_ASSOCIATED_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_TAG_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_STATEMENT_ASSOCIATED_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_FILM_FILM_ASSOCIATED_WRITER
            - ROLE_BASE_ADMIN_STATEMENT_FILM_PROJECTION_ASSOCIATED_WRITER