<?php

namespace FDC\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FilmFifPersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmFifPersonneRepository extends EntityRepository
{
}
