services:

    mdf.transformers.content_to_elastica_transformer:
        class: FDC\MarcheDuFilmBundle\Transformer\ContentToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]

    mdf.transformers.media_to_elastica_transformer:
        class: FDC\MarcheDuFilmBundle\Transformer\MediaToElasticaTransformer
        arguments: [{}, '@event_dispatcher']
        calls:
            - [setPropertyAccessor, ['@fos_elastica.property_accessor']]
