services:

    #Homepage
    base.admin.homepage:
        class: Base\AdminBundle\Admin\HomepageAdmin
        arguments: [~, Base\CoreBundle\Entity\Homepage, BaseAdminBundle:HomepageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Homepage, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
          - [ setTranslationDomain, ['BaseAdminBundle']]

    # GROUP GENERAL
    base.admin.tag:
        class: Base\AdminBundle\Admin\TagAdmin
        arguments: [~, Base\CoreBundle\Entity\Tag, BaseAdminBundle:TagAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.general, label: entity.tag, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.web_tv:
        class: Base\AdminBundle\Admin\WebTvAdmin
        arguments: [~, Base\CoreBundle\Entity\WebTv, BaseAdminBundle:WebTvAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.general, label: entity.web_tv, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
            - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.contact_theme:
        class: Base\AdminBundle\Admin\ContactThemeAdmin
        arguments: [~, Base\CoreBundle\Entity\ContactTheme, BaseAdminBundle:ContactThemeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.general, label: entity.contact_theme, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
            - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.social_wall:
        class: Base\AdminBundle\Admin\SocialWallAdmin
        arguments: [~, Base\CoreBundle\Entity\SocialWall, BaseAdminBundle:SocialWallAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.general, label: entity.social_wall, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
            - [ setTranslationDomain, ['BaseAdminBundle']]

    # GROUP EVENT
    base.admin.event:
        class: Base\AdminBundle\Admin\EventAdmin
        arguments: [~, Base\CoreBundle\Entity\Event, BaseAdminBundle:EventAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.event, label: entity.event, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    # GROUP STATEMENT
    base.admin.statement_article:
        class: Base\AdminBundle\Admin\StatementArticleAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementArticle, BaseAdminBundle:StatementArticleAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.statement, label: entity.statement_article, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_video:
        class: Base\AdminBundle\Admin\StatementVideoAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementVideo, BaseAdminBundle:StatementVideoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.statement, label: entity.statement_video, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_image:
        class: Base\AdminBundle\Admin\StatementImageAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementImage, BaseAdminBundle:StatementImageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.statement, label: entity.statement_image, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_audio:
        class: Base\AdminBundle\Admin\StatementAudioAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementAudio, BaseAdminBundle:StatementAudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.statement, label: entity.statement_audio, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_theme:
        class: Base\AdminBundle\Admin\StatementThemeAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementTheme, BaseAdminBundle:StatementThemeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.statement, label: entity.statement_theme, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
            - [ setTranslationDomain, ['BaseAdminBundle']]

    #GROUP NEWS
    base.admin.news_article:
        class: Base\AdminBundle\Admin\NewsArticleAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsArticle, BaseAdminBundle:NewsArticleAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.news, label: entity.news_article, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_video:
        class: Base\AdminBundle\Admin\NewsVideoAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsVideo, BaseAdminBundle:NewsVideoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.news, label: entity.news_video, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_image:
        class: Base\AdminBundle\Admin\NewsImageAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsImage, BaseAdminBundle:NewsImageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.news, label: entity.news_image, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_audio:
        class: Base\AdminBundle\Admin\NewsAudioAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsAudio, BaseAdminBundle:NewsAudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.news, label: entity.news_audio, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_theme:
        class: Base\AdminBundle\Admin\NewsThemeAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsTheme, BaseAdminBundle:NewsThemeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.news, label: entity.news_theme, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    #MEDIAS

    base.admin.media_image:
        class: Base\AdminBundle\Admin\MediaImageAdmin
        arguments: [~, Base\CoreBundle\Entity\MediaImage, BaseAdminBundle:MediaImageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.media, label: entity.media_image, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.media_audio:
        class: Base\AdminBundle\Admin\MediaAudioAdmin
        arguments: [~, Base\CoreBundle\Entity\MediaAudio, BaseAdminBundle:MediaAudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.media, label: entity.media_audio, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.media_video:
         class: Base\AdminBundle\Admin\MediaVideoAdmin
         arguments: [~, Base\CoreBundle\Entity\MediaVideo, BaseAdminBundle:MediaVideoAdmin]
         tags:
             - {name: sonata.admin, manager_type: orm, group: dashboard.group.media, label: entity.media_video, label_translator_strategy: sonata.admin.label.strategy.underscore}
         calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    #SOIF
    base.admin.film_film:
        class: Base\AdminBundle\Admin\FilmFilmAdmin
        arguments: [~, Base\CoreBundle\Entity\FilmFilm, BaseAdminBundle:FilmFilmAdmin]
        tags:
             - {name: sonata.admin, manager_type: orm, group: dashboard.group.soif, label: entity.film_film, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
            - [ setTranslationDomain, ["BaseAdminBundle"]]


    base.admin.film_projection:
        class: Base\AdminBundle\Admin\FilmProjectionAdmin
        arguments: [~, Base\CoreBundle\Entity\FilmProjection, BaseAdminBundle:FilmProjectionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.soif, label: entity.film_projection, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.film_person:
        class: Base\AdminBundle\Admin\FilmPersonAdmin
        arguments: [~, Base\CoreBundle\Entity\FilmPerson, BaseAdminBundle:FilmPersonAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.soif, label: entity.film_person, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
            - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.film_atelier:
        class: Base\AdminBundle\Admin\FilmAtelierAdmin
        arguments: [~, Base\CoreBundle\Entity\FilmAtelier, BaseAdminBundle:FilmAtelierAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.soif, label: entity.film_atelier, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.country:
        class: Base\AdminBundle\Admin\CountryAdmin
        arguments: [~, Base\CoreBundle\Entity\Country, BaseAdminBundle:CountryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.soif, label: entity.country, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    #HIDDEN
    base.admin.news_widget_image_dummy:
        class: Base\AdminBundle\Admin\NewsWidgetImageDummyAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsWidgetImage, BaseAdminBundle:NewsWidgetImageDummyAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: News Widget Image, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.media_tag:
        class: Base\AdminBundle\Admin\MediaTagAdmin
        arguments: [~, Base\CoreBundle\Entity\MediaTag, BaseAdminBundle:MediaTagAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: dashboard.group.media, label: MediaTag, show_in_dashboard: false}

    base.admin.media:
        class: Base\AdminBundle\Admin\MediaAdmin
        arguments: [~, Base\CoreBundle\Entity\Media, BaseAdminBundle:MediaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Media, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.gallery:
        class: Base\AdminBundle\Admin\GalleryAdmin
        arguments: [~, Base\CoreBundle\Entity\Gallery, BaseAdminBundle:GalleryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Gallery, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.gallery_media:
        class: Base\AdminBundle\Admin\GalleryMediaAdmin
        arguments: [~, Base\CoreBundle\Entity\GalleryMedia, BaseAdminBundle:GalleryMediaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: GalleryMediaAdmin, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]


    base.admin.news:
        class: Base\AdminBundle\Admin\NewsAdmin
        arguments: [~, Base\CoreBundle\Entity\News, BaseAdminBundle:NewsAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: News, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_tag:
        class: Base\AdminBundle\Admin\NewsTagAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsTag, BaseAdminBundle:NewsTagAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsTag, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_news_associated:
        class: Base\AdminBundle\Admin\NewsNewsAssociatedAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsNewsAssociated, BaseAdminBundle:NewsNewsAssociatedAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsNewsAssociated, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_film_projection_associated:
        class: Base\AdminBundle\Admin\NewsFilmProjectionAssociatedAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsFilmProjectionAssociated, BaseAdminBundle:NewsFilmProjectionAssociatedAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsFilmProjectionAssociated, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.news_film_film_associated:
        class: Base\AdminBundle\Admin\NewsFilmFilmAssociatedAdmin
        arguments: [~, Base\CoreBundle\Entity\NewsFilmFilmAssociated, BaseAdminBundle:NewsFilmFilmAssociatedAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsFilmFilmAssociated, show_in_dashboard: false}
        calls:
            - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.film_film_media:
        class: Base\AdminBundle\Admin\FilmFilmMediaAdmin
        arguments: [~, Base\CoreBundle\Entity\FilmFilmMedia, BaseAdminBundle:FilmFilmMediaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: SOIF, label: FilmFilmMedia, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.film_media:
        class: Base\AdminBundle\Admin\FilmMediaAdmin
        arguments: [~, Base\CoreBundle\Entity\FilmMedia, BaseAdminBundle:FilmMediaAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: SOIF, label: FilmMedia, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    #STATEMENT
    base.admin.statement_widget_image_dummy:
            class: Base\AdminBundle\Admin\NewsWidgetImageDummyAdmin
            arguments: [~, Base\CoreBundle\Entity\NewsWidgetImage, BaseAdminBundle:NewsWidgetImageDummyAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: admin, label: News Widget Image, show_in_dashboard: false}
            calls:
                 - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement:
        class: Base\AdminBundle\Admin\StatementAdmin
        arguments: [~, Base\CoreBundle\Entity\Statement, BaseAdminBundle:StatementAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Statement, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_tag:
        class: Base\AdminBundle\Admin\StatementTagAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementTag, BaseAdminBundle:StatementTagAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: StatementTag, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_statement_associated:
        class: Base\AdminBundle\Admin\StatementStatementAssociatedAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementStatementAssociated, BaseAdminBundle:StatementStatementAssociatedAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: StatementStatementAssociated, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_film_projection_associated:
        class: Base\AdminBundle\Admin\StatementFilmProjectionAssociatedAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementFilmProjectionAssociated, BaseAdminBundle:StatementFilmProjectionAssociatedAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: StatementFilmProjectionAssociated, show_in_dashboard: false}
        calls:
             - [ setTranslationDomain, ['BaseAdminBundle']]

    base.admin.statement_film_film_associated:
        class: Base\AdminBundle\Admin\StatementFilmFilmAssociatedAdmin
        arguments: [~, Base\CoreBundle\Entity\StatementFilmFilmAssociated, BaseAdminBundle:StatementFilmFilmAssociatedAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: StatementFilmFilmAssociated, show_in_dashboard: false}
        calls:
            - [ setTranslationDomain, ['BaseAdminBundle']]