services:
    base.admin.event.locale_listener:
        class: Base\AdminBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    base.admin.event.homepage_listener:
        class: Base\AdminBundle\EventListener\HomepageListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }