services:
    base.admin.event.locale_listener:
        class: Base\AdminBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    base.admin.event.homepage_listener:
        class: Base\AdminBundle\EventListener\HomepageListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    base.admin.event.news_listener:
        class: Base\AdminBundle\EventListener\NewsListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    base.admin.event.entity_listener:
        class: Base\AdminBundle\EventListener\EntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }

        calls:
            - [ setLocales, ['%locales%']]

    base.admin.event.media_listener:
        class: Base\AdminBundle\EventListener\MediaListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    base.admin.event.ccm_media_listener:
        class: Base\AdminBundle\EventListener\CcmMediaListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    base.admin.event.mobile_notification_listener:
        class: Base\AdminBundle\EventListener\MobileNotificationListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }