services:
    base.admin.event.locale_listener:
        class: Base\AdminBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    base.admin.event.homepage_listener:
        class: Base\AdminBundle\EventListener\HomepageListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    base.admin.event.news_listener:
        class: Base\AdminBundle\EventListener\NewsListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }

    base.admin.event.entity_listener:
        class: Base\AdminBundle\EventListener\EntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }

    base.admin.event.media_listener:
        class: Base\AdminBundle\EventListener\MediaListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }
        arguments: [@service_container]