services:
    #news
    base.admin.form.news_widget_type:
        class: Base\AdminBundle\Form\Type\NewsWidgetType
        tags:
            - { name: form.type, alias: 'news_widget_type'}

    base.admin.form.news_widget_text_type:
        class: Base\AdminBundle\Form\Type\NewsWidgetTextType
        tags:
            - { name: form.type, alias: 'news_widget_text_type'}

    base.admin.form.news_widget_quote_type:
        class: Base\AdminBundle\Form\Type\NewsWidgetQuoteType
        tags:
            - { name: form.type, alias: 'news_widget_quote_type'}

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.news_widget_audio_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\NewsWidgetAudioType
        tags:
            - { name: form.type, alias: 'news_widget_audio_type'}
        calls:
            - ['setSonataAdmin', ['@sonata.media.admin.gallery']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.news_widget_image_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\NewsWidgetImageType
        tags:
            - { name: form.type, alias: 'news_widget_image_type'}
        calls:
            - ['setNewsWidgetImageDummyAdmin', ['@base.admin.news_widget_image_dummy']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.news_widget_image_dual_align_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\NewsWidgetImageDualAlignType
        tags:
            - { name: form.type, alias: 'news_widget_image_dual_align_type'}
        calls:
            - ['setNewsWidgetImageDummyAdmin', ['@base.admin.news_widget_image_dummy']]

    base.admin.form.news_widget_video_type:
            class: Base\AdminBundle\Form\Type\NewsWidgetVideoType
            tags:
                - { name: form.type, alias: 'news_widget_video_type'}

    base.admin.form.news_widget_video_youtube_type:
            class: Base\AdminBundle\Form\Type\NewsWidgetVideoYoutubeType
            tags:
                - { name: form.type, alias: 'news_widget_video_youtube_type'}

    #event services
    base.admin.form.event_widget_type:
        class: Base\AdminBundle\Form\Type\EventWidgetType
        tags:
            - { name: form.type, alias: 'event_widget_type'}

    base.admin.form.event_widget_text_type:
        class: Base\AdminBundle\Form\Type\EventWidgetTextType
        tags:
            - { name: form.type, alias: 'event_widget_text_type'}

    base.admin.form.event_widget_quote_type:
        class: Base\AdminBundle\Form\Type\EventWidgetQuoteType
        tags:
            - { name: form.type, alias: 'event_widget_quote_type'}

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.event_widget_audio_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\EventWidgetAudioType
        tags:
            - { name: form.type, alias: 'event_widget_audio_type'}
        calls:
            - ['setSonataAdmin', ['@sonata.media.admin.gallery']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.event_widget_image_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\EventWidgetImageType
        tags:
            - { name: form.type, alias: 'event_widget_image_type'}
        calls:
            - ['setEventWidgetImageDummyAdmin', ['@base.admin.event_widget_image_dummy']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.event_widget_image_dual_align_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\EventWidgetImageDualAlignType
        tags:
            - { name: form.type, alias: 'event_widget_image_dual_align_type'}
        calls:
            - ['setEventWidgetImageDummyAdmin', ['@base.admin.event_widget_image_dummy']]

    base.admin.form.event_widget_video_type:
            class: Base\AdminBundle\Form\Type\EventWidgetVideoType
            tags:
                - { name: form.type, alias: 'event_widget_video_type'}

    base.admin.form.event_widget_video_youtube_type:
            class: Base\AdminBundle\Form\Type\EventWidgetVideoYoutubeType
            tags:
                - { name: form.type, alias: 'event_widget_video_youtube_type'}

    #Statement services
    base.admin.form.statement_widget_type:
        class: Base\AdminBundle\Form\Type\StatementWidgetType
        tags:
            - { name: form.type, alias: 'statement_widget_type'}

    base.admin.form.statement_widget_text_type:
        class: Base\AdminBundle\Form\Type\StatementWidgetTextType
        tags:
            - { name: form.type, alias: 'statement_widget_text_type'}

    base.admin.form.statement_widget_quote_type:
        class: Base\AdminBundle\Form\Type\StatementWidgetQuoteType
        tags:
            - { name: form.type, alias: 'statement_widget_quote_type'}

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.statement_widget_audio_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\StatementWidgetAudioType
        tags:
            - { name: form.type, alias: 'statement_widget_audio_type'}
        calls:
            - ['setStatementWidgetAudioDummyAdmin', ['@base.admin.statement_widget_audio_dummy']]


    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.statement_widget_image_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\StatementWidgetImageType
        tags:
            - { name: form.type, alias: 'statement_widget_image_type'}
        calls:
            - ['setStatementWidgetImageDummyAdmin', ['@base.admin.statement_widget_image_dummy']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.statement_widget_image_dual_align_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\StatementWidgetImageDualAlignType
        tags:
            - { name: form.type, alias: 'statement_widget_image_dual_align_type'}
        calls:
            - ['setStatementWidgetImageDummyAdmin', ['@base.admin.statement_widget_image_dummy']]

    base.admin.form.statement_widget_video_type:
            class: Base\AdminBundle\Form\Type\StatementWidgetVideoType
            tags:
                - { name: form.type, alias: 'statement_widget_video_type'}

    base.admin.form.statement_widget_video_youtube_type:
            class: Base\AdminBundle\Form\Type\StatementWidgetVideoYoutubeType
            tags:
                - { name: form.type, alias: 'statement_widget_video_youtube_type'}
                
    #Info services
    base.admin.form.info_widget_type:
        class: Base\AdminBundle\Form\Type\InfoWidgetType
        tags:
            - { name: form.type, alias: 'info_widget_type'}

    base.admin.form.info_widget_text_type:
        class: Base\AdminBundle\Form\Type\InfoWidgetTextType
        tags:
            - { name: form.type, alias: 'info_widget_text_type'}

    base.admin.form.info_widget_quote_type:
        class: Base\AdminBundle\Form\Type\InfoWidgetQuoteType
        tags:
            - { name: form.type, alias: 'info_widget_quote_type'}

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.info_widget_audio_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\InfoWidgetAudioType
        tags:
            - { name: form.type, alias: 'info_widget_audio_type'}
        calls:
            - ['setInfoWidgetAudioDummyAdmin', ['@base.admin.info_widget_audio_dummy']]


    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.info_widget_image_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\InfoWidgetImageType
        tags:
            - { name: form.type, alias: 'info_widget_image_type'}
        calls:
            - ['setInfoWidgetImageDummyAdmin', ['@base.admin.info_widget_image_dummy']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.info_widget_image_dual_align_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\InfoWidgetImageDualAlignType
        tags:
            - { name: form.type, alias: 'info_widget_image_dual_align_type'}
        calls:
            - ['setInfoWidgetImageDummyAdmin', ['@base.admin.info_widget_image_dummy']]

    base.admin.form.info_widget_video_type:
        class: Base\AdminBundle\Form\Type\InfoWidgetVideoType
        tags:
            - { name: form.type, alias: 'info_widget_video_type'}

    base.admin.form.info_widget_video_youtube_type:
        class: Base\AdminBundle\Form\Type\InfoWidgetVideoYoutubeType
        tags:
            - { name: form.type, alias: 'info_widget_video_youtube_type'}

    base.admin.form.press_guide_widget_type:
        class: Base\AdminBundle\Form\Type\PressGuideWidgetType
        tags:
            - { name: form.type, alias: 'press_guide_widget_type'}

    base.admin.form.press_guide_widget_picto_type:
        class: Base\AdminBundle\Form\Type\PressGuideWidgetPictoType
        tags:
            - { name: form.type, alias: 'press_guide_widget_picto_type'}

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.press_guide_widget_image_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\PressGuideWidgetImageType
        tags:
            - { name: form.type, alias: 'press_guide_widget_image_type'}
        calls:
            - ['setPressGuideWidgetImageDummyAdmin', ['@base.admin.press_guide_widget_image_dummy']]

    base.admin.form.press_guide_widget_column_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\PressGuideWidgetColumnType
        tags:
            - { name: form.type, alias: 'press_guide_widget_column_type'}
        calls:
            - ['setPressGuideWidgetColumnDummyAdmin', ['@base.admin.press_guide_widget_column_dummy']]


    base.admin.form.press_download_section_widget_type:
        class: Base\AdminBundle\Form\Type\PressDownloadSectionWidgetType
        tags:
            - { name: form.type, alias: 'press_download_section_widget_type'}

    base.admin.form.press_download_section_widget_video_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\PressDownloadSectionWidgetVideoType
        tags:
            - { name: form.type, alias: 'press_download_section_widget_video_type'}
        calls:
            - ['setPressDownloadSectionWidgetVideoDummyAdmin', ['@base.admin.press_download_section_widget_video_dummy']]

    base.admin.form.press_download_section_widget_photo_type:
        scope: prototype
        class: Base\AdminBundle\Form\Type\PressDownloadSectionWidgetPhotoType
        tags:
            - { name: form.type, alias: 'press_download_section_widget_photo_type'}
        calls:
            - ['setPressDownloadSectionWidgetPhotoDummyAdmin', ['@base.admin.press_download_section_widget_photo_dummy']]

    base.admin.form.press_download_section_widget_file_type:
        class: Base\AdminBundle\Form\Type\PressDownloadSectionWidgetFileType
        tags:
            - { name: form.type, alias: 'press_download_section_widget_file_type'}

    base.admin.form.press_download_section_widget_document_type:
        class: Base\AdminBundle\Form\Type\PressDownloadSectionWidgetDocumentType
        tags:
            - { name: form.type, alias: 'press_download_section_widget_document_type'}
