security:
    role_hierarchy:
        ROLE_TRANSLATOR_FR:
        - ROLE_TRANSLATOR

        ROLE_TRANSLATOR_EN:
        - ROLE_TRANSLATOR

        ROLE_TRANSLATOR_ES:
        - ROLE_TRANSLATOR

        ROLE_TRANSLATOR_ZH:
        - ROLE_TRANSLATOR
