security:
    role_hierarchy:
        ROLE_FDC_TRANSLATOR_MASTER:
            - ROLE_FDC_TRANSLATOR_FR
            - ROLE_FDC_TRANSLATOR_EN
            - ROLE_FDC_TRANSLATOR_ES
            - ROLE_FDC_TRANSLATOR_ZH

        ROLE_HOMEPAGE:
        - ROLE_BASE_ADMIN_HOMEPAGE_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_SLIDE_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_TOP_VIDEOS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_TOP_WEB_TVS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_FILMS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_NEWS_LIST
        - ROLE_BASE_ADMIN_INFO_LIST
        - ROLE_BASE_ADMIN_STATEMENT_LIST
        - ROLE_BASE_ADMIN_FILM_FILM_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_LIST
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST
        - ROLE_BASE_ADMIN_WEB_TV_LIST

        ROLE_SOIF:
        - ROLE_BASE_ADMIN_FILM_FILM_ADMIN
        - ROLE_BASE_ADMIN_FILM_FILM_TAG_ADMIN
        - ROLE_BASE_ADMIN_FILM_PROJECTION_ADMIN
        - ROLE_BASE_ADMIN_FILM_PERSON_ADMIN
        - ROLE_BASE_ADMIN_FILM_ATELIER_ADMIN
        - ROLE_BASE_ADMIN_COUNTRY_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_NEWS_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_INFO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_LIST
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_LIST
        - ROLE_SOIF_UPDATE

        ROLE_NEWS:
        - ROLE_BASE_ADMIN_NEWS_ADMIN
        - ROLE_BASE_ADMIN_NEWS_TAG_ADMIN
        - ROLE_BASE_ADMIN_NEWS_ARTICLE_ADMIN
        - ROLE_BASE_ADMIN_NEWS_VIDEO_ADMIN
        - ROLE_BASE_ADMIN_NEWS_IMAGE_ADMIN
        - ROLE_BASE_ADMIN_NEWS_AUDIO_ADMIN
        - ROLE_BASE_ADMIN_EVENT_LIST
        - ROLE_BASE_ADMIN_EVENT_FILM_PROJECTION_ASSOCIATED_LIST
        - ROLE_BASE_ADMIN_MEDIA_FILM_PROJECTION_ASSOCIATED_LIST
        - ROLE_BASE_ADMIN_NEWS_NEWS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_NEWS_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_NEWS_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_LIST
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_LIST
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_THEME_LIST
        - ROLE_BASE_ADMIN_GALLERY_LIST
        - ROLE_BASE_ADMIN_FILM_FILM_LIST

        ROLE_STATEMENTS:
        - ROLE_BASE_ADMIN_STATEMENT_ARTICLE_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_VIDEO_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_IMAGE_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_AUDIO_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_TAG_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_STATEMENT_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_THEME_LIST
        - ROLE_BASE_ADMIN_GALLERY_LIST
        - ROLE_BASE_ADMIN_FILM_FILM_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_LIST
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_LIST
        - ROLE_BASE_ADMIN_EVENT_LIST
        - ROLE_BASE_ADMIN_EVENT_FILM_PROJECTION_ASSOCIATED_LIST
        - ROLE_BASE_ADMIN_MEDIA_FILM_PROJECTION_ASSOCIATED_LIST

        ROLE_INFOS:
        - ROLE_BASE_ADMIN_INFO_ARTICLE_ADMIN
        - ROLE_BASE_ADMIN_INFO_VIDEO_ADMIN
        - ROLE_BASE_ADMIN_INFO_IMAGE_ADMIN
        - ROLE_BASE_ADMIN_INFO_AUDIO_ADMIN
        - ROLE_BASE_ADMIN_INFO_ADMIN
        - ROLE_BASE_ADMIN_INFO_TAG_ADMIN
        - ROLE_BASE_ADMIN_INFO_INFO_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_INFO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_INFO_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_THEME_LIST
        - ROLE_BASE_ADMIN_GALLERY_LIST
        - ROLE_BASE_ADMIN_FILM_FILM_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_LIST
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_LIST
        - ROLE_BASE_ADMIN_EVENT_LIST
        - ROLE_BASE_ADMIN_EVENT_FILM_PROJECTION_ASSOCIATED_LIST
        - ROLE_BASE_ADMIN_MEDIA_FILM_PROJECTION_ASSOCIATED_LIST

        ROLE_EVENT:
        - ROLE_BASE_ADMIN_EVENT_ADMIN
        - ROLE_BASE_ADMIN_EVENT_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_EVENT_WIDGET_SUBTITLE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_WIDGET_MOSAIC_MOVIE_ADMIN
        - ROLE_BASE_ADMIN_WIDGET_MOSAIC_MOVIE_FILM_FILM_ADMIN


        ROLE_THEME:
        - ROLE_FDC_TRANSLATOR_MASTER
        - ROLE_BASE_ADMIN_THEME_ADMIN

        ROLE_AUDIO:
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_ADMIN
        - ROLE_BASE_ADMIN_TAG_ADMIN
        - ROLE_BASE_ADMIN_EVENT_LIST
        - ROLE_BASE_ADMIN_FDC_PAGE_EVENT_ADMIN

        ROLE_ORANGE:
        - ROLE_BASE_ADMIN_ORANGE_STUDIO_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_SERIES_AND_CIE_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_PROGRAMMATION_OCS_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_VOD_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_STUDIO_ADMIN
        # relations
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_LIST_CREATE_EDIT_DELETE
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST_CREATE_EDIT_DELETE
        - ROLE_BASE_ADMIN_FILM_FILM_LIST
        - ROLE_BASE_ADMIN_THEME_LIST
        - ROLE_BASE_ADMIN_NEWS_ARTICLE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_MEDIA_ADMIN

        ROLE_ORANGE_TRANSLATOR:
        - ROLE_BASE_ADMIN_ORANGE_STUDIO_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_SERIES_AND_CIE_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_PROGRAMMATION_OCS_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_VOD_ADMIN
        - ROLE_BASE_ADMIN_ORANGE_STUDIO_ADMIN
        # relations
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST_CREATE_EDIT_DELETE
        - ROLE_BASE_ADMIN_FILM_FILM_LIST
        - ROLE_BASE_ADMIN_THEME_LIST


        ROLE_TRANSLATOR:
        - ROLE_ADMIN
        - ROLE_JMS_TRANSLATION
        - ROLE_FDC_TRANSLATOR_MASTER
        - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ADMIN
        - ROLE_SONATA_MEDIA_ADMIN_GALLERY_ADMIN
        - ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_CONTACT_THEME_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_EVENT_ROUTES_LIST_EDIT
        - ROLE_BASE_ADMIN_HOMEPAGE_LIST_EDIT
        - ROLE_BASE_ADMIN_HOMEPAGE_SLIDE_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_TOP_VIDEOS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_TOP_WEB_TVS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_FILMS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_TAG_LIST_EDIT
        - ROLE_BASE_ADMIN_WEB_TV_ADMIN
        - ROLE_BASE_ADMIN_WEB_TV_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_CANNES_CLASSICS_LIST_EDIT
        - ROLE_BASE_ADMIN_EVENT_LIST_EDIT
        - ROLE_BASE_ADMIN_THEME_LIST_EDIT
        - ROLE_BASE_ADMIN_EVENT_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_EVENT_WIDGET_SUBTITLE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GROUP_SEO_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_CHANNELS_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_LIVE_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_LIVE_WEB_TV_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_LIVE_MEDIA_VIDEO_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_TRAILERS_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_LA_SELECTION_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_JURY_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_AWARD_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_AWARD_OTHER_SELECTION_SECTIONS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_EVENT_LIST_EDIT
        - ROLE_BASE_ADMIN_FILM_JURY_TYPE_LIST_EDIT
        - ROLE_BASE_ADMIN_STATEMENT_ARTICLE_LIST_EDIT
        - ROLE_BASE_ADMIN_STATEMENT_VIDEO_LIST_EDIT
        - ROLE_BASE_ADMIN_STATEMENT_IMAGE_LIST_EDIT
        - ROLE_BASE_ADMIN_STATEMENT_AUDIO_LIST_EDIT
        - ROLE_BASE_ADMIN_INFO_ARTICLE_LIST_EDIT
        - ROLE_BASE_ADMIN_INFO_VIDEO_LIST_EDIT
        - ROLE_BASE_ADMIN_INFO_IMAGE_LIST_EDIT
        - ROLE_BASE_ADMIN_INFO_AUDIO_LIST_EDIT
        - ROLE_BASE_ADMIN_THEME_LIST_EDIT
        - ROLE_BASE_ADMIN_NEWS_ARTICLE_LIST_EDIT
        - ROLE_BASE_ADMIN_NEWS_VIDEO_LIST_EDIT
        - ROLE_BASE_ADMIN_NEWS_IMAGE_LIST_EDIT
        - ROLE_BASE_ADMIN_NEWS_AUDIO_LIST_EDIT
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_LIST_EDIT
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_LIST_EDIT
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WAITING_LIST_EDIT
        - ROLE_BASE_ADMIN_AMAZON_REMOTE_FILE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST_EDIT
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FILM_SELECTION_SECTION_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_TAG_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_LIST_EDIT
        - ROLE_BASE_ADMIN_MEDIA_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_NEWS_LIST_EDIT
        - ROLE_BASE_ADMIN_NEWS_TAG_ADMIN
        - ROLE_BASE_ADMIN_NEWS_NEWS_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_NEWS_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_NEWS_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FILM_FILM_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_FILM_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_LIST_EDIT
        - ROLE_BASE_ADMIN_STATEMENT_TAG_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_STATEMENT_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_INFO_LIST_EDIT
        - ROLE_BASE_ADMIN_INFO_TAG_ADMIN
        - ROLE_BASE_ADMIN_INFO_INFO_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_INFO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_INFO_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_CONTACT_PAGE_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_HOMEPAGE_ADMIN
        - ROLE_BASE_ADMIN_PRESS_HOMEPAGE_SECTION_ADMIN
        - ROLE_BASE_ADMIN_PRESS_HOMEPAGE_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_PRESS_HOMEPAGE_DOWNLOAD_ADMIN
        - ROLE_BASE_ADMIN_PRESS_ACCREDIT_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_ACCREDIT_HAS_PROCEDURE_ADMIN
        - ROLE_BASE_ADMIN_PRESS_ACCREDIT_PROCEDURE_ADMIN
        - ROLE_BASE_ADMIN_PRESS_GUIDE_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_MEDIA_LIBRARY_ADMIN
        - ROLE_BASE_ADMIN_PRESS_DOWNLOAD_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_DOWNLOAD_SECTION_ADMIN
        - ROLE_BASE_ADMIN_PRESS_DOWNLOAD_HAS_SECTION_ADMIN
        - ROLE_BASE_ADMIN_PRESS_PROJECTION_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_CINEMA_MAP_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_CINEMA_ROOM_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_CINEMA_MAP_ROOM_LIST_EDIT
        - ROLE_BASE_ADMIN_PRESS_STATEMENT_INFO_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_NEWS_ARTICLES_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_NEWS_AUDIOS_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_NEWS_IMAGES_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_NEWS_VIDEOS_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_PREPARE_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_PARTICIPATE_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_PARTICIPATE_SECTION_WIDGET_TYPEFOUR_DUMMY_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_PARTICIPATE_SECTION_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_PARTICIPATE_HAS_SECTION_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PARTICIPATE_PAGE_LIST_EDIT
        - ROLE_BASE_ADMIN_FDC_PAGE_LA_SELECTION_CANNES_CLASSICS_LIST_EDIT
        - ROLE_BASE_ADMIN_WIDGET_MOVIE_ADMIN
        - ROLE_BASE_ADMIN_WIDGET_MOVIE_FILM_FILM_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_LA_SELECTION_CINEMA_PLAGE_LIST_EDIT
        - ROLE_ORANGE_TRANSLATOR
        - ROLE_HOMEPAGE
        - ROLE_BASE_ADMIN_FDC_PAGE_FOOTER_LIST_EDIT
        - ROLE_BASE_ADMIN_FAQ_THEME_LIST_EDIT
        - ROLE_BASE_ADMIN_FAQ_PAGE_LIST_EDIT
        # https://redmine.ohwee.fr/issues/7996
        - ROLE_BASE_ADMIN_HOMEPAGE_CORPORATE_ADMIN
        - ROLE_BASE_ADMIN_HOMEPAGE_CORPORATE_SLIDE_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_MEDIATHEQUE_ADMIN
        - ROLE_BASE_ADMIN_CORPO_MEDIATHEQUE_ADMIN
        - ROLE_BASE_ADMIN_CORPO_MEDIATHEQUE_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_CORPO_WHO_ARE_WE_ADMIN
        - ROLE_BASE_ADMIN_CORPO_SEARCH_ADMIN
        - ROLE_BASE_ADMIN_CORPO_MOVIE_INSCRIPTION_ADMIN
        - ROLE_BASE_ADMIN_CORPO_MOVIE_INSCRIPTION_HAS_PROCEDURE_ADMIN
        - ROLE_BASE_ADMIN_CORPO_MOVIE_INSCRIPTION_TRANSLATION_ADMIN
        - ROLE_BASE_ADMIN_CORPO_MOVIE_INSCRIPTION_PROCEDURE_ADMIN
        - ROLE_BASE_ADMIN_CORPO_MOVIE_INSCRIPTION_PROCEDURE_TRANSLATION_ADMIN
        - ROLE_BASE_ADMIN_CORPO_ACCREDIT_ADMIN
        - ROLE_BASE_ADMIN_CORPO_ACCREDIT_PROCEDURE_ADMIN
        - ROLE_BASE_ADMIN_CORPO_ACCREDIT_HAS_PROCEDURE_ADMIN
        - ROLE_BASE_ADMIN_FILM_FESTIVAL_MEDIA_IMAGE_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_CORPO_FESTIVAL_HISTORY_ADMIN
        - ROLE_BASE_ADMIN_CORPO_PALME_OR_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_TEAMS_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_MEMBERS_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_MEMBERS_GROUP_ASSOCIATION_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_MEMBERS_WIDGET_GROUP_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAMS_ASSOCIATION_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_TEAMS_ASSOCIATION_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_DEPARTEMENTS_ADMIN
        - ROLE_BASE_ADMIN_CORPO_TEAM_DEPARTEMENTS_ASSOCIATION_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_TAG_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_PDF_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_POSITION_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_POSITION_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_ONE_COLUMN_IMAGE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_TWO_COLUMNS_IMAGE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_TWO_COLUMNS_TWO_IMAGE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_THREE_COLUMNS_IMAGE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_THREE_COLUMNS_TWO_IMAGE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_THREE_COLUMNS_THREE_IMAGE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_ONE_COLUMN_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_TWO_COLUMNS_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_TWO_COLUMNS_TWO_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_THREE_COLUMNS_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_THREE_COLUMNS_TWO_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_SECTION_THREE_COLUMNS_THREE_DUMMY_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_BUTTON_GROUP_SECTION_COLLECTION_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_BUTTON_FILE_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_BUTTON_SECTION_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_BUTTON_FILE_COLLECTION_ADMIN
        - ROLE_BASE_ADMIN_GRAPHICAL_CHARTER_BUTTON_GROUP_ADMIN
        - ROLE_BASE_ADMIN_MOBILE_NOTIFICATION_ADMIN
