security:
    role_hierarchy:
        ROLE_CONTRIBUTOR_VIDEOS_AUDIOS:
        - ROLE_FDC_TRANSLATOR_MASTER
        - ROLE_BASE_ADMIN_THEME_ADMIN
        - ROLE_ADMIN
        - ROLE_BASE_ADMIN_THEME_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_TAG_ADMIN
        - ROLE_BASE_ADMIN_NEWS_TAG_ADMIN
        - ROLE_BASE_ADMIN_STATEMENT_TAG_ADMIN
        - ROLE_BASE_ADMIN_INFO_TAG_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_ADMIN
        - ROLE_HOMEPAGE
        #webtvlive
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_LIVE_ADMIN
        - ROLE_BASE_ADMIN_WEB_TV_LIST
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_LIST
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_LIST
        - ROLE_BASE_ADMIN_MEDIA_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FILM_PROJECTION_LIST
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_CHANNELS_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_LIVE_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_LIVE_WEB_TV_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_FDC_PAGE_WEB_TV_LIVE_MEDIA_VIDEO_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_GROUP_SEO_ADMIN
        #chaînes
        - ROLE_FDC_TRANSLATOR_MASTER
        - ROLE_BASE_ADMIN_WEB_TV_ADMIN
        #theme
        - ROLE_FDC_TRANSLATOR_MASTER
        - ROLE_BASE_ADMIN_THEME_ADMIN
        #tag
        - ROLE_BASE_ADMIN_TAG_ADMIN
        - ROLE_AUDIO
        - ROLE_TRANSLATE_FR
        - ROLE_TRANSLATE_EN
        - ROLE_TRANSLATE_ES
        - ROLE_TRANSLATE_ZH
        # SOIF
        - ROLE_BASE_ADMIN_FILM_FILM_ADMIN
        - ROLE_SOIF_UPDATE



















