event:
    type:       rest
    resource:   Base\ApiBundle\Controller\EventController

film:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmController

film_atelier:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmAtelierController

film_award:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmAwardController

film_person:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmPersonController

film_jury:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmJuryController

film_jury_type:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmJuryTypeController

film_selection:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmSelectionController

film_projection:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmProjectionController

film_trailer:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmTrailerController

news:
    type:       rest
    resource:   Base\ApiBundle\Controller\NewsController

web_tv:
    type:       rest
    resource:   Base\ApiBundle\Controller\WebTvController

social_wall_mobile:
    type:       rest
    resource:   Base\ApiBundle\Controller\SocialWallMobileController

social_wall_instagram:
    type:       rest
    resource:   Base\ApiBundle\Controller\SocialWallInstagramController

social_wall_twitter:
    type:       rest
    resource:   Base\ApiBundle\Controller\SocialWallTwitterController