event:
    type:       rest
    resource:   Base\ApiBundle\Controller\EventController

film:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmController

film_atelier:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmAtelierController

palmares:
    type:       rest
    resource:   Base\ApiBundle\Controller\PalmaresController

film_person:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmPersonController

film_home:
    type:       rest
    resource:   Base\ApiBundle\Controller\HomeController

film_jury:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmJuryController

film_jury_type:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmJuryTypeController

film_selection:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmSelectionController

film_selection_section:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmSelectionSectionController

film_projection:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmProjectionController

film_trailer:
    type:       rest
    resource:   Base\ApiBundle\Controller\FilmTrailerController

news:
    type:       rest
    resource:   Base\ApiBundle\Controller\NewsController

web_tv:
    type:       rest
    resource:   Base\ApiBundle\Controller\WebTvController

social_wall:
    type:       rest
    resource:   Base\ApiBundle\Controller\SocialWallController

social_wall_instagram:
    type:       rest
    resource:   Base\ApiBundle\Controller\SocialWallInstagramController

social_wall_twitter:
    type:       rest
    resource:   Base\ApiBundle\Controller\SocialWallTwitterController

today_images:
    type:       rest
    resource:   Base\ApiBundle\Controller\TodayImagesController

classics:
    type:       rest
    resource:   Base\ApiBundle\Controller\ClassicsController

orange_series_and_cie:
    type:       rest
    resource:   Base\ApiBundle\Controller\OrangeSeriesAndCieController

orange_programmation_ocs:
    type:       rest
    resource:   Base\ApiBundle\Controller\OrangeProgrammationOCSController