services:
    base.api.core_manager:
        class: Base\ApiBundle\Manager\CoreManager
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]
            - ['setApiVersion', ['%api_version%']]
            - ['setApiPageOffset', ['%api_page_offset%']]
            - ['setKnpPaginator', ['@knp_paginator']]
    base.api.serialization_listener:
        class: Base\ApiBundle\EventListener\SerializationListener
        tags:
            - {name: jms_serializer.event_subscriber}
        calls:
            - ['setMediaImageProvider', ['@sonata.media.provider.image']]