#http://a2lix.fr/bundles/translation-form/#bundle-installation
a2lix_translation_form:
    locale_provider: default
    locales: "%locales%"
    default_locale: "%locale_default_translation%"
    required_locales: ['%locale_default_translation%']
    manager_registry: doctrine
    #templating: "A2lixTranslationFormBundle::default.html.twig"
    templating: "FDCAdminBundle:TranslationFormBundle:default.html.twig"