fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
    registration:
            form:
                type: fdc_press_password
                handler: fdc_press.form.handler.lockedcontent
    service:
        user_manager: sonata.user.orm.user_manager