jms_translation:
    configs:
        fdc_event:
            dirs: [%kernel.root_dir%/../src/FDC/EventBundle]
            output_dir: %kernel.root_dir%/../src/FDC/EventBundle/Resources/translations
            ignored_domains: [FDCPressBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: []
            extractors: []
        fdc_corporate:
            dirs: [%kernel.root_dir%/../src/FDC/CorporateBundle]
            output_dir: %kernel.root_dir%/../src/FDC/CorporateBundle/Resources/translations
            ignored_domains: [FDCPressBundle, FDCEventBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: []
            extractors: []
        fdc_press:
            dirs: [%kernel.root_dir%/../src/FDC/PressBundle]
            output_dir: %kernel.root_dir%/../src/FDC/PressBundle/Resources/translations
            ignored_domains: [FDCEventBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: []
            extractors: []
        fdc_event_mobile:
            dirs: [%kernel.root_dir%/../src/FDC/EventMobileBundle]
            output_dir: %kernel.root_dir%/../src/FDC/EventMobileBundle/Resources/translations
            ignored_domains: [FDCEventBundle, FDCPressBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [Form]
            extractors: []
        fdc_press_mobile:
            dirs: [%kernel.root_dir%/../src/FDC/EventMobileBundle, %kernel.root_dir%/../src/FDC/PressMobileBundle]
            output_dir: %kernel.root_dir%/../src/FDC/PressMobileBundle/Resources/translations
            ignored_domains: [FDCEventBundle, FDCPressBundle, FDCEventMobileBundle]
            domains: [FDCPressMobileBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [Form]
            extractors: []
        mdf:
            dirs: [%kernel.root_dir%/../src/FDC/MarcheDuFilmBundle]
            output_dir: %kernel.root_dir%/../src/FDC/MarcheDuFilmBundle/Resources/translations
            ignored_domains: [FDCCorporateBundle, FDCEventBundle, FDCPressBundle, FDCEventMobileBundle, FDCPressMobileBundle, BaseAdminBundle, CourtMetrageBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [wordpress-plugin]
            extractors: []
        ccm:
            dirs: [%kernel.root_dir%/../src/FDC/CourtMetrageBundle]
            output_dir: %kernel.root_dir%/../src/FDC/CourtMetrageBundle/Resources/translations
            ignored_domains: [FDCCorporateBundle, FDCEventBundle, FDCPressBundle, FDCEventMobileBundle, FDCPressMobileBundle, BaseAdminBundle, MarcheDuFilmBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [wordpress-plugin]
            extractors: []
        app:
            dirs: [%kernel.root_dir%/../src/FDC/EventBundle, %kernel.root_dir%/../src/FDC/CorporateBundle, %kernel.root_dir%/../src/FDC/PressBundle, %kernel.root_dir%/../src/FDC/EventMobileBundle]
            output_dir: %kernel.root_dir%/../app/Resources/translations
            ignored_domains: []
            excluded_names: ["*TestCase.php", "*Test.php"]
            domains: [routes]
            excluded_dirs: []
            extractors: [jms_i18n_routing]
            output_format: xliff
