jms_translation:
    configs:
        admin:
            dirs: [%kernel.root_dir%/../src/FDC/AdminBundle]
            output_dir: %kernel.root_dir%/../src/FDC/AdminBundle
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            extractors: [sonata_admin]