jms_translation:
    configs:
        fdc_event:
            dirs: [%kernel.root_dir%/../src/FDC/EventBundle]
            output_dir: %kernel.root_dir%/../src/FDC/EventBundle/Resources/translations
            ignored_domains: [FDCPressBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: []
            extractors: []
        fdc_press:
            dirs: [%kernel.root_dir%/../src/FDC/PressBundle]
            output_dir: %kernel.root_dir%/../src/FDC/PressBundle/Resources/translations
            ignored_domains: [FDCEventBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: []
            extractors: []
        fdc_event_mobile:
            dirs: [%kernel.root_dir%/../src/FDC/EventMobileBundle]
            output_dir: %kernel.root_dir%/../src/FDC/EventMobileBundle/Resources/translations
            ignored_domains: [FDCEventBundle, FDCPressBundle]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [Form]
            extractors: []
        app:
            dirs: [%kernel.root_dir%/../src/FDC/EventBundle, %kernel.root_dir%/../src/FDC/PressBundle, %kernel.root_dir%/../src/FDC/EventMobileBundle]
            output_dir: %kernel.root_dir%/../app/Resources/translations
            ignored_domains: []
            excluded_names: ["*TestCase.php", "*Test.php"]
            domains: [routes]
            excluded_dirs: []
            extractors: [jms_i18n_routing]
            output_format: xliff
