sonata_admin:
    title: FDC Administration
    security:
        handler: sonata.admin.security.handler.acl
        information:
            WRITER:    [VIEW, LIST, CREATE, EDIT]
            EDITOR: [VIEW, LIST, CREATE, EDIT, DELETE, UNDELETE]
            TRANSLATOR: [VIEW, EDIT, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    dashboard:
        blocks:
           # - { position: top, class: col-md-12, type: base_admin.block.sites }
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [dashboard.group.news]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [dashboard.group.general]
        # setting messages as label_catalogue for groups because JmsTranslation can't handle variables translation.
        # Related translations available in app/Resources/translations
        groups:
            dashboard.group.general:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.news:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.statement:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.info:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.media:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.soif:
                items: ~
                label_catalogue: BaseAdminBundle
            sonata_user:
                items: ~
                label_catalogue: SonataUserBundle
            sonata_media:
                items: ~
                label_catalogue: SonataMediaBundle

    templates:
        short_object_description:  'ApplicationSonataAdminBundle:Helper:short-object-description.html.twig'