sonata_admin:
    title: FDC Administration
    security:
        handler: sonata.admin.security.handler.acl
        information:
            # must be added for role listed in groups/security_*.yml to works
            LIST: [LIST]
            LIST_EDIT: [LIST, EDIT]
            LIST_CREATE_EDIT_DELETE: [LIST, CREATE, EDIT, DELETE]
            ADMIN:    [VIEW, LIST, CREATE, EDIT, DELETE, UNDELETE, EXPORT, OPERATOR]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, EDIT, DELETE, UNDELETE, EXPORT, OPERATOR]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR]
    dashboard:
        blocks:
            #DASHBOARD TRANSLATOR
            -
                position: top
                class: col-md-12
                type: base.admin.block.search
                roles: [ ROLE_TRANSLATOR, ROLE_TRANSLATOR_MASTER ]

            #EVERYONE EXCEPT ORANGE AND TRANSLATOR DASHBOARD
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [dashboard.group.news]
                roles: [ ROLE_ALL_ADMIN, ROLE_ADMIN_FDC, ROLE_COMMUNITY_MANAGER, ROLE_CONTRIBUTOR_PHOTOS, ROLE_CONTRIBUTOR_VIDEOS_AUDIOS, ROLE_JOURNALIST, ROLE_SUPER_ADMIN ]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [dashboard.group.general]
                roles: [ ROLE_ALL_ADMIN, ROLE_ADMIN_FDC, ROLE_COMMUNITY_MANAGER, ROLE_CONTRIBUTOR_PHOTOS, ROLE_CONTRIBUTOR_VIDEOS_AUDIOS, ROLE_JOURNALIST, ROLE_SUPER_ADMIN ]
        # setting messages as label_catalogue for groups because JmsTranslation can't handle variables translation.
        # Related translations available in app/Resources/translations
        groups:
            admin.group.mdf:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_presse:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_qui_sommes_nous:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_goes_to_cannes:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_mixers:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_next:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_doc_corner:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_producers_network:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.mdf_producers_workshop:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.general:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.ccm.footer:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.ccm.news:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.ccm.seo_tetieres:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.ccm.short:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.ccm.pros:
                items: ~
                label_catalogue: BaseAdminBundle
            admin.group.ccm.participer:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.event:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.statement:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.info:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.cannes_classics:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.cinema_plage:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.media:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.soif:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.seo:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.press:
                items: ~
                label_catalogue: BaseAdminBundle
            dashboard.group.participate:
                items: ~
                label_catalogue: BaseAdminBundle
            sonata_user:
                items: ~
                label_catalogue: SonataUserBundle
            sonata_media:
                items: ~
                label_catalogue: SonataMediaBundle
    assets:
        javascripts:

            # Defaults:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
            - bundles/baseadmin/js/admin.js

    templates:
        short_object_description:  'ApplicationSonataAdminBundle:Helper:short-object-description.html.twig'