sonata_seo:
    encoding:         UTF-8
    page:
        metas:
            name:
                description: ''

            property:

                'title':              Festival de Cannes %fdc_year%
                'og:site_name':       Festival de Cannes %fdc_year%
                'og:description':     ''

            charset:
                UTF-8:    ''

        head: