trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    toolbar: ['clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'styles', 'tools']
    toolbar_groups:
        document: ['Source']