imports:
    - { resource: config.yml }

#framework:
#    templating:
#        assets_base_urls: http://affif-sitepublic-vendor-prod.s3-website-eu-west-1.amazonaws.com/

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            excluded_404s:
                - ^/
            handler:      grouped
        grouped:
            type:               group
            members:            [streamed, buffered]
        buffered:
          type: buffer
          handler: swift
        streamed:
            type:               stream
            path:               "%kernel.logs_dir%/%kernel.environment%.log"
            level:              debug
        swift:
            type:               swift_mailer
            from_email:         logs@ohwee.fr
            to_email:           %email_sysadmin_fdc%
            subject:            "Festival de Cannes / MAJ SOIF Error"
            level:              debug
        console:
            type:  console