imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: bundles/a2lix_i18n_doctrine.yml }
    - { resource: bundles/a2lix_translation_form.yml }
    - { resource: bundles/nelmio_api_doc.yml }
    - { resource: bundles/fos_user.yml }
    - { resource: bundles/fos_rest.yml }
    - { resource: bundles/ivory_ck_editor.yml }
    - { resource: bundles/jms_di_extra.yml }
    - { resource: bundles/jms_translation.yml }
    - { resource: bundles/jms_i18n_translation.yml }
    - { resource: bundles/sonata_admin.yml }
    - { resource: bundles/sonata_block.yml }
    - { resource: bundles/sonata_doctrine_orm_admin.yml }
    - { resource: bundles/sonata_intl.yml }
    - { resource: bundles/sonata_media.yml }
    - { resource: bundles/sonata_media_services.yml }
    - { resource: bundles/sonata_seo.yml }
    - { resource: bundles/stof_doctrine_extensions.yml }
    - { resource: twig.yml }
    # old roles
    - { resource: roles/security_all.yml }
    - { resource: roles/security_fdc.yml }
    - { resource: roles/security_soif.yml }
    - { resource: roles/security_translation.yml }
    # news roles
    - { resource: roles/groups/security_admin_fdc.yml }
    - { resource: roles/groups/security_community_manager.yml }
    - { resource: roles/groups/security_contributor_photos.yml }
    - { resource: roles/groups/security_contributor_videos_audios.yml }
    - { resource: roles/groups/security_master_translator.yml }
    - { resource: roles/groups/security_translator.yml }
    - { resource: roles/groups/security_super_admin.yml }
    - { resource: roles/groups/security_admin_pages.yml }
    - { resource: roles/groups/security_journalist.yml }
    - { resource: roles/groups/security_orange.yml }

parameters:
    #sonata
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\Entity\UserAdmin
    #security
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.pdo
        cookie_lifetime: 3600
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'InfiniteFormBundle::collection_theme.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    bundles:        [ SonataAdminBundle, BaseAdminBundle, FDCEventBundle, FDCEventMobileBundle, FDCPressBundle ]
    use_controller: true
    filters:
        cssrewrite:
            apply_to: "\.css$"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                # New custom filter
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true
                dql:
                    numeric_functions:
                        Rand: Base\CoreBundle\Doctrine\Rand
                    datetime_functions:
                        Date_Format: Base\CoreBundle\Doctrine\DateFormat


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Guzzle Configuration
misd_guzzle:
    service_builder:
        class:              "Guzzle\Service\Builder\ServiceBuilder"
        configuration_file: "%kernel.root_dir%/config/webservices.json"

eko_feed:
    translation_domain: FDCEventBundle # Optional, if you want to use a custom translation domain
    feeds:
        article:
            title:       'Festival de Cannes'
            description: 'Feed from Festival de Cannes'
            link:        ''
            encoding:    'utf-8'
            author:      ~ # Only required for Atom feeds
