imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: roles/security_all.yml }
    - { resource: roles/security_fdc.yml }
    - { resource: roles/security_soif.yml }
    - { resource: roles/security_translation.yml }
    - { resource: services.yml }
    - { resource: bundles/a2lix_i18n_doctrine.yml }
    - { resource: bundles/a2lix_translation_form.yml }
    - { resource: bundles/nelmio_api_doc.yml }
    - { resource: bundles/fos_user.yml }
    - { resource: bundles/fos_rest.yml }
    - { resource: bundles/ivory_ck_editor.yml }
    - { resource: bundles/jms_di_extra.yml }
    - { resource: bundles/jms_translation.yml }
    - { resource: bundles/jms_i18n_translation.yml }
    - { resource: bundles/sonata_admin.yml }
    - { resource: bundles/sonata_block.yml }
    - { resource: bundles/sonata_doctrine_orm_admin.yml }
    - { resource: bundles/sonata_intl.yml }
    - { resource: bundles/sonata_media.yml }
    - { resource: bundles/sonata_media_services.yml }
    - { resource: bundles/sonata_seo.yml }
    - { resource: bundles/stof_doctrine_extensions.yml }

parameters:
    #sonata
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\Entity\UserAdmin
    #security
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.pdo
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'InfiniteFormBundle::collection_theme.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
    globals:
        locales: "%locales%"
        locale_fallback: "%%locale_fallback%"
        locale_default_translation: "%locale_default_translation%"
        fdc_app_android_download_url: "%fdc_app_android_download_url%"
        fdc_app_ios_download_url: "%fdc_app_ios_download_url%"
        header_fdc: "%header_fdc%"
        header_cine: "%header_cine%"
        header_ccm: "%header_ccm%"
        header_mdf: "%header_mdf%"
        header_account: "%header_account%"
        partner_chopard: "%partner_chopard%"
        partner_loreal: "%partner_loreal%"
        partner_hp: "%partner_hp%"
        partner_kering: "%partner_kering%"
        partner_renault: "%partner_renault%"
        partner_mastercard: "%partner_mastercard%"
        footer_boutique: "%footer_boutique%"
        social_appli: "%social_appli%"
        social_facebook: "%social_facebook%"
        social_twitter: "%social_twitter%"
        social_instagram: "%social_instagram%"
        social_tumblr: "%social_tumblr%"
        social_rss: "%social_rss%"
        social_youtube: "%social_youtube%"
        social_dailymotion: "%social_dailymotion%"
        social_podcast: "%social_podcast%"
        jwplayer_key: "%jwplayer_key%"
        admin_routes_translation_legend_without_master: %admin_routes_translation_legend_without_master%
        admin_routes_translation_legend: %admin_routes_translation_legend%
        admin_routes_translation_lock: %admin_routes_translation_lock%
        admin_homepage_id: %admin_homepage_id%
        admin_fdc_page_web_tv_live_id: %admin_fdc_page_web_tv_live_id%
        admin_fdc_page_web_tv_channels_id: %admin_fdc_page_web_tv_channels_id%
        admin_press_homepage_id: %admin_press_homepage_id%
        admin_press_guide_id: %admin_press_guide_id%
        admin_press_contact_id: %admin_press_contact_id%
        admin_press_download_id: %admin_press_download_id%
        admin_press_medialibrary_id: %admin_press_medialibrary_id%
        admin_press_accredit_id: %admin_press_accredit_id%
        admin_press_cinemamap_id: %admin_press_cinemamap_id%
        admin_press_projection_id: %admin_press_projection_id%
        admin_press_statementinfo_id: %admin_press_statementinfo_id%
        admin_fdc_page_web_tv_trailers_competition_id: %admin_fdc_page_web_tv_trailers_competition_id%
        admin_fdc_page_web_tv_trailers_certain_regard_id: %admin_fdc_page_web_tv_trailers_certain_regard_id%
        admin_fdc_page_web_tv_trailers_hors_competition_id: %admin_fdc_page_web_tv_trailers_hors_competition_id%
        admin_fdc_page_web_tv_trailers_seances_speciales_id: %admin_fdc_page_web_tv_trailers_seances_speciales_id%
        admin_fdc_page_web_tv_trailers_cinefondation_id: %admin_fdc_page_web_tv_trailers_cinefondation_id%
        admin_fdc_page_web_tv_trailers_courts_metrages_id: %admin_fdc_page_web_tv_trailers_courts_metrages_id%
        admin_fdc_page_web_tv_trailers_cannes_classics_id: %admin_fdc_page_web_tv_trailers_cannes_classics_id%
        admin_fdc_page_web_tv_trailers_cinema_plage_id: %admin_fdc_page_web_tv_trailers_cinema_plage_id%
        s3_server_global: http://%s3_global_bucket_name%.s3-website-%s3_global_region%.amazonaws.com/
        s3_server_video: http://%s3_video_bucket_name%.s3-website-%s3_video_region%.amazonaws.com/
        s3_server_audio: http://%s3_audio_bucket_name%.s3-website-%s3_audio_region%.amazonaws.com/

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    bundles:        [ SonataAdminBundle, BaseAdminBundle, FDCEventBundle, FDCPressBundle ]
    use_controller: true
    filters:
        cssrewrite:
            apply_to: "\.css$"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                # New custom filter
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true
                dql:
                    numeric_functions:
                        Rand: Base\CoreBundle\Doctrine\Rand
                    datetime_functions:
                        Date_Format: Base\CoreBundle\Doctrine\DateFormat


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Guzzle Configuration
misd_guzzle:
    service_builder:
        class:              "Guzzle\Service\Builder\ServiceBuilder"
        configuration_file: "%kernel.root_dir%/config/webservices.json"
