services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - { db_username: %database_user%, db_password: %database_password% }

    app.exception_controller:
        class: FDC\MarcheDuFilmBundle\Controller\ExceptionController
        arguments: ['@twig', '%kernel.debug%', '@mdf.manager.404', '@mdf.manager.header_footer', '%fdc_marche_du_film_domain%']
        calls:
            - [ setCcmDomain, ['%fdc_court_metrage_domain%']]
            - [ setCcmExceptionManager, ['@ccm.manager.exception']]
            - [ setEventMobileDomain, ['%fdc_event_mobile_domain%']]
