services:
    base.admin.form.ccm_homepage_sejour_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\HomepageSejourType
        tags:
            - { name: form.type, alias: 'ccm_homepage_sejour_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_homepage_sejour_top_dummy']]
            - ['setMediaImageAdmin', ['@base.admin.media_image']]

    base.admin.form.ccm_homepage_actualite_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\HomepageActualiteType
        tags:
            - { name: form.type, alias: 'ccm_homepage_actualite_type'}
        calls:
            - ['setSonataAdminTheme', ['@base.admin.ccm_homepage_actualite_theme_top_dummy']]
            - ['setThemeAdmin', ['@base.admin.theme']]
            - ['setImageAdmin', ['@base.admin.media_image']]

    base.admin.form.ccm_catalog_push_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CatalogPushType
        tags:
            - { name: form.type, alias: 'ccm_catalog_push_type'}

    base.admin.form.ccm_homepage_slider_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\HomepageSliderType
        tags:
            - { name: form.type, alias: 'ccm_homepage_slider_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_homepage_slider_top_dummy']]
            - ['setMediaImageAdmin', ['@base.admin.media_image']]

    base.admin.form.ccm_homepage_push_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\HomepagePushType
        tags:
            - { name: form.type, alias: 'ccm_homepage_push_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_homepage_push_top_dummy']]
            - ['setMediaImageAdmin', ['@base.admin.media_image']]

    # News Widget Forms
    base.admin.form.ccm_news_widget_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_type'}

    base.admin.form.ccm_news_widget_text_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetTextType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_text_type'}

    base.admin.form.ccm_news_widget_description_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetDescriptionType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_description_type'}

    base.admin.form.ccm_news_widget_quote_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetQuoteType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_quote_type'}

    base.admin.form.ccm_news_widget_signature_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetSignatureType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_signature_type'}

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_news_widget_audio_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetAudioType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_audio_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_news_widget_audio_dummy']]
            - ['setMediaAudioAdmin', ['@base.admin.media_audio']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_news_widget_image_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetImageType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_image_type'}
        calls:
            - ['setNewsWidgetImageDummyAdmin', ['@base.admin.ccm_news_widget_image_dummy']]
            - ['setGalleryAdmin', ['@base.admin.gallery']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_news_widget_image_dual_align_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetImageDualAlignType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_image_dual_align_type'}
        calls:
            - ['setNewsWidgetImageDummyAdmin', ['@base.admin.ccm_news_widget_image_dual_align_dummy']]
            - ['setGalleryDualAlignAdmin', ['@base.admin.gallery_dual_align']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_news_widget_gallery_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetGalleryType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_gallery_type'}
        calls:
            - ['setNewsWidgetGalleryDummyAdmin', ['@base.admin.ccm_news_widget_gallery_dummy']]
            - ['setGalleryAdmin', ['@base.admin.gallery']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_news_widget_video_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetVideoType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_video_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_news_widget_video_dummy']]
            - ['setMediaVideoAdmin', ['@base.admin.media_video']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_news_widget_video_youtube_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmNewsWidgetVideoYoutubeType
        tags:
            - { name: form.type, alias: 'ccm_news_widget_video_youtube_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_news_widget_video_youtube_dummy']]
            - ['setMediaImageSimpleAdmin', ['@base.admin.media_image_simple']]
    # end News Widget Forms

    # Short film corner widget forms
    base.admin.form.ccm_sfc_widget_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_type'}

    base.admin.form.ccm_sfc_widget_text_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetTextType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_text_type'}

    base.admin.form.ccm_sfc_widget_subtitle_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetSubtitleType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_subtitle_type'}

    base.admin.form.ccm_sfc_widget_quote_type:
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetQuoteType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_quote_type'}

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_sfc_widget_audio_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetAudioType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_audio_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_sfc_widget_audio_dummy']]
            - ['setMediaAudioAdmin', ['@base.admin.media_audio']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_sfc_widget_image_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetImageType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_image_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_sfc_widget_image_dummy']]
            - ['setGalleryAdmin', ['@base.admin.gallery']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_sfc_widget_image_dual_align_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetImageDualAlignType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_image_dual_align_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_sfc_widget_image_dual_align_dummy']]
            - ['setGalleryDualAlignAdmin', ['@base.admin.gallery_dual_align']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_sfc_widget_video_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetVideoType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_video_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_sfc_widget_video_dummy']]
            - ['setMediaVideoAdmin', ['@base.admin.media_video']]

    # need to add scope prototype to avoid ScopeCrossingInjectionException
    base.admin.form.ccm_sfc_widget_video_youtube_type:
        scope: prototype
        class: FDC\CourtMetrageBundle\Form\Type\CcmShortFilmCornerWidgetVideoYoutubeType
        tags:
            - { name: form.type, alias: 'ccm_sfc_widget_video_youtube_type'}
        calls:
            - ['setSonataAdmin', ['@base.admin.ccm_sfc_widget_video_youtube_dummy']]
            - ['setMediaImageSimpleAdmin', ['@base.admin.media_image_simple']]
    # end Short film corner widget forms