services:
    ccm.manager.competition:
        class: FDC\CourtMetrageBundle\Manager\CompetitionManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    ccm.manager.news:
        class: FDC\CourtMetrageBundle\Manager\NewsManager
        arguments: [ '@doctrine.orm.entity_manager' ]

    ccm.manager.menu:
        class: FDC\CourtMetrageBundle\Manager\MenuManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    ccm.manager.participate:
        class: FDC\CourtMetrageBundle\Manager\ParticipateManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    ccm.manager.homepage:
        class: FDC\CourtMetrageBundle\Manager\HomepageManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    ccm.manager.pros:
        class: FDC\CourtMetrageBundle\Manager\ProsManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
