services:
    base.twig.menu_extension:
      class: FDC\CourtMetrageBundle\Twig\MenuExtension
      tags:
          - name: twig.extension
      calls:
          - ['setRouter', ['@router']]

    base.twig.filter_extension:
      class: FDC\CourtMetrageBundle\Twig\FilterExtension
      tags:
          - name: twig.extension
