film:
    type:       rest
    resource:   FDC\ApiBundle\Controller\FilmController

film_atelier:
    type:       rest
    resource:   FDC\ApiBundle\Controller\FilmAtelierController

film_award:
    type:       rest
    resource:   FDC\ApiBundle\Controller\FilmAwardController

film_person:
    type:       rest
    resource:   FDC\ApiBundle\Controller\FilmPersonController

film_projection:
    type:       rest
    resource:   FDC\ApiBundle\Controller\FilmProjectionController

film_prize:
    type:       rest
    resource:   FDC\ApiBundle\Controller\FilmPrizeController

film_jury:
    type:       rest
    resource:   FDC\ApiBundle\Controller\FilmJuryController

news:
    type:       rest
    resource:   FDC\ApiBundle\Controller\NewsController