services:
#    fdc.listener.doctrine:
#        class: FDC\CoreBundle\Listener\DoctrineListener
#        tags:
#            - { name: doctrine.event_listener, event: onFlush }
#        calls:
#            - ['setLocaleDefaultTranslation', ['%locale_default_translation%']]