services:
    fdc.admin.news_article:
        class: FDC\AdminBundle\Admin\NewsArticleAdmin
        arguments: [~, FDC\CoreBundle\Entity\NewsArticle, FDCAdminBundle:NewsArticleAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsArticle}

    fdcadmin.news_audio:
        class: FDC\AdminBundle\Admin\NewsAudioAdmin
        arguments: [~, FDC\CoreBundle\Entity\NewsAudio, FDCAdminBundle:NewsAudioAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: NewsAudio}

    fdc.admin.theme:
        class: FDC\AdminBundle\Admin\ThemeAdmin
        arguments: [~, FDC\CoreBundle\Entity\Theme, FDCAdminBundle:ThemeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Theme}
