services:
    fdc.form.news_widget_type:
        class: FDC\AdminBundle\Form\Type\NewsWidgetType
        tags:
            - { name: form.type, alias: 'news_widget_type'}

    fdc.form.news_widget_text_type:
        class: FDC\AdminBundle\Form\Type\NewsWidgetTextType
        tags:
            - { name: form.type, alias: 'news_widget_text_type'}

    fdc.form.news_widget_audio_type:
        scope: prototype
        class: FDC\AdminBundle\Form\Type\NewsWidgetAudioType
        tags:
            - { name: form.type, alias: 'news_widget_audio_type'}
        calls:
            - ['setSonataAdmin', ['@sonata.media.admin.media']]

    fdc.form.news_widget_image_type:
            class: FDC\AdminBundle\Form\Type\NewsWidgetImageType
            tags:
                - { name: form.type, alias: 'news_widget_image_type'}

    fdc.form.news_widget_video_type:
            class: FDC\AdminBundle\Form\Type\NewsWidgetVideoType
            tags:
                - { name: form.type, alias: 'news_widget_video_type'}