services:
    #http://jmsyst.com/bundles/JMSTranslationBundle/master/webinterface
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension