services:
    fdc.soif.core_manager:
        abstract: true
        class: FDC\SoifBundle\Manager\CoreManager
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]
            - ['setLogger', ['@logger']]
            - ['setUploadDirectoryHD', ['%soif_upload_directory_hd%']]
            - ['setUploadDirectorySD', ['%soif_upload_directory_sd%']]
            - ['setWebserviceUrl', ['%soif_url%']]

    fdc.soif.festival_manager:
        parent: fdc.soif.core_manager
        class: FDC\SoifBundle\Manager\FestivalManager
        arguments: []

    fdc.soif.media_manager:
        parent: fdc.soif.core_manager
        class: FDC\SoifBundle\Manager\MediaManager
        arguments: []