services:
    #soif logger
    fdc.soif.logger_manager:
        class: FDC\SoifBundle\Manager\LoggerManager
        calls:
            - ['setSoifLog', ['%soif_log%']]
            - ['setSoifLogDirectory', ['%soif_log_directory%']]
    #soif core
    fdc.soif.core_manager:
        abstract: true
        class: FDC\SoifBundle\Manager\CoreManager
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]
            - ['setLogger', ['@logger']]
            - ['setSoifLogger', ['@fdc.soif.logger_manager']]
            - ['setWebserviceUrl', ['%soif_url%']]
    #soif children
    fdc.soif.award_manager:
        parent: fdc.soif.core_manager
        class: FDC\SoifBundle\Manager\AwardManager
        arguments: ['@fdc.soif.festival_manager', '@fdc.soif.prize_manager']

    fdc.soif.festival_manager:
        parent: fdc.soif.core_manager
        class: FDC\SoifBundle\Manager\FestivalManager
        arguments: []

    fdc.soif.media_manager:
        parent: fdc.soif.core_manager
        class: FDC\SoifBundle\Manager\MediaManager
        arguments: ['@fdc.soif.festival_manager', '@fdc.soif.media_stream_manager']

    fdc.soif.media_stream_manager:
        parent: fdc.soif.core_manager
        class: FDC\SoifBundle\Manager\MediaStreamManager
        arguments: []
        calls:
            - ['setSonataMediaManager', ['@sonata.media.manager.media']]
            - ['setSoifUploadDirectory', ['%soif_upload_directory%']]

    fdc.soif.prize_manager:
        parent: fdc.soif.core_manager
        class: FDC\SoifBundle\Manager\PrizeManager
        arguments: []