<?php

namespace Base\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GraphicalCharterButtonSectionTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraphicalCharterButtonSectionTranslationRepository extends EntityRepository
{
}
